################################# Default configuration ###################
baseURL = "https://eureka.trading/"
title = "Eureka Trading"
theme = "meghna-hugo"
DefaultContentLanguage = "zh"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
#[[params.plugins.css]]
#link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"

############################# Navigation ##################################
[[menu.main]]
name = "Business"
URL = "services"
weight = 1

#[[menu.main]]
#name = "Customers"
#URL = "cutomers"
#weight = 2

[[menu.main]]
name = "About"
URL = "about"
weight = 3

#[[menu.main]]
#name = "Blog"
#URL = "blog"
#weight = 4

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5

#### external / static link ####
[[menu.static]]
name = "Login"
URL = "https://eureka.trading/dashboard"
weight = 6

############################# Default Parameters ##########################
[params]
#logo = "images/logo.png"
# Meta data
description = "Eureka Trading Official Site"
author = "Eureka Trading"
# Google Analitycs
google_analitycs_id = "" # Your ID
# post share
#post_share = true

# preloader
#[params.preloader]
#enable = true
#preloader = "images/logo.png"

############################# social icons ##########################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
#link = "#"

################################ Chinese Language ########################
[Languages.zh]
languageName = "Zh"
languageCode = "zh-cn"
contentDir = "content/chinese"
weight = 1
home = "Home"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
